site_name: A-Frame Locomotion Docs
site_url: https://aframe-locomotion.fern.solutions/
theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - navigation.tabs
  custom_dir: docs/.overrides

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/noerihuisman
    - icon: fontawesome/brands/mastodon
      link: https://arvr.social/@noerihuisman
    - icon: fontawesome/brands/github
      link: https://github.com/mrxz

repo_url: https://github.com/mrxz/aframe-locomotion