site_name: A-Frame Locomotion Docs
site_url: https://aframe-locomotion.fern.solutions/docs/
theme:
  name: material
  features:
    - content.code.copy


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences